# Generated by Django 5.1.3 on 2024-11-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imap_server', models.CharField(max_length=255)),
                ('imap_port', models.IntegerField()),
                ('imap_login', models.CharField(max_length=255)),
                ('imap_password', models.CharField(max_length=255)),
                ('smtp_server', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField()),
                ('smtp_login', models.CharField(max_length=255)),
                ('smtp_password', models.CharField(max_length=255)),
            ],
        ),
    ]
