# Generated by Django 5.1.3 on 2024-11-23 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_receiver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailbox',
            options={'verbose_name': 'Mailbox', 'verbose_name_plural': 'Mailboxes'},
        ),
        migrations.AddField(
            model_name='mailbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailbox',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='imap_encryption',
            field=models.CharField(choices=[('SSL', 'SSL'), ('TLS', 'TLS'), ('NONE', 'None')], default='SSL', max_length=10),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='smtp_encryption',
            field=models.CharField(choices=[('SSL', 'SSL'), ('TLS', 'TLS'), ('NONE', 'None')], default='TLS', max_length=10),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='imap_login',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='imap_port',
            field=models.IntegerField(default=993),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='imap_server',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='smtp_login',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='smtp_server',
            field=models.CharField(max_length=100),
        ),
    ]
