# Generated by Django 5.1.3 on 2024-11-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_receiver', '0002_alter_mailbox_options_mailbox_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='imap_password',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='smtp_password',
            field=models.CharField(max_length=1024),
        ),
    ]
