# Generated by Django 5.1.3 on 2024-11-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_receiver', '0003_alter_mailbox_imap_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='imap_password',
            field=models.CharField(max_length=2024),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='smtp_password',
            field=models.CharField(max_length=2024),
        ),
    ]
