# Generated by Django 5.1.3 on 2024-11-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_receiver', '0004_alter_mailbox_imap_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255, verbose_name='Nadawca')),
                ('recipient', models.CharField(blank=True, max_length=255, null=True, verbose_name='Odbiorca')),
                ('subject', models.CharField(blank=True, max_length=512, null=True, verbose_name='Temat')),
                ('received_date', models.DateTimeField(verbose_name='Data otrzymania')),
                ('content', models.TextField(verbose_name='Treść wiadomości')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID wiadomości')),
                ('content_type', models.CharField(max_length=100, verbose_name='Typ zawartości')),
                ('mime_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Wersja MIME')),
                ('return_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ścieżka zwrotna')),
                ('dkim_signature', models.TextField(blank=True, null=True, verbose_name='Podpis DKIM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia w bazie')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Czy przetworzona')),
                ('processing_errors', models.TextField(blank=True, null=True, verbose_name='Błędy przetwarzania')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emaile',
                'ordering': ['-received_date'],
                'indexes': [models.Index(fields=['-received_date'], name='mail_receiv_receive_ab29c1_idx'), models.Index(fields=['sender'], name='mail_receiv_sender_7f8c7f_idx'), models.Index(fields=['is_processed'], name='mail_receiv_is_proc_74b5be_idx')],
            },
        ),
    ]
