# Generated by Django 5.1.3 on 2024-11-23 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_receiver', '0005_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='email',
            name='content',
            field=models.TextField(db_collation='utf8mb4_unicode_ci', verbose_name='Treść wiadomości'),
        ),
        migrations.AlterField(
            model_name='email',
            name='received_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data otrzymania'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=512, null=True, verbose_name='Temat'),
        ),
    ]
