# Generated by Django 5.1.3 on 2024-11-23 22:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_receiver', '0006_email_date_alter_email_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='received_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data synchronizacji'),
        ),
    ]
