# Generated by Django 5.1.3 on 2024-11-24 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_receiver', '0008_emailattachment_email_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_path', models.CharField(help_text='Pełna ścieżka folderu', max_length=255)),
                ('name', models.CharField(help_text='Nazwa folderu', max_length=100)),
                ('delimiter', models.CharField(help_text='Separator używany w ścieżce', max_length=5)),
                ('attributes', models.CharField(help_text='Atrybuty folderu', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='mail_receiver.mailbox')),
            ],
            options={
                'verbose_name': 'Folder mailowy',
                'verbose_name_plural': 'Foldery mailowe',
                'unique_together': {('mailbox', 'full_path')},
            },
        ),
    ]
