# Generated by Django 5.1.3 on 2024-11-25 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_receiver', '0010_email_mail_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='mail_folder',
            field=models.ForeignKey(default='mail.Archive', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mail_receiver.mailfolder'),
        ),
    ]
