# Generated by Django 5.1.3 on 2024-11-25 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_receiver', '0012_alter_email_mail_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='mail_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mail_receiver.mailfolder'),
        ),
    ]
