# Generated by Django 5.1.3 on 2024-11-26 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_receiver', '0013_alter_email_mail_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='mail_folder',
        ),
        migrations.AddField(
            model_name='email',
            name='mailbox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mail_receiver.mailbox', verbose_name='Skrzynka pocztowa'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['mailbox'], name='mail_receiv_mailbox_04fd78_idx'),
        ),
    ]
