# Generated by Django 5.1.3 on 2024-11-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_receiver', '0014_remove_email_mail_folder_email_mailbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='smtp_encryption',
            field=models.CharField(choices=[('SSL', 'SSL'), ('TLS', 'TLS'), ('STARTTLS', 'STARTTLS'), ('NONE', 'None')], default='TLS', max_length=10),
        ),
    ]
