# Generated by Django 5.1.3 on 2024-11-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_receiver', '0015_alter_mailbox_smtp_encryption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='imap_encryption',
            field=models.CharField(choices=[('SSL', 'SSL'), ('TLS', 'TLS'), ('STARTTLS', 'STARTTLS'), ('NONE', 'None')], default='SSL', max_length=10),
        ),
    ]
