# Generated by Django 5.1.3 on 2025-01-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_receiver', '0016_alter_mailbox_imap_encryption'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='ticket',
            field=models.CharField(blank=True, db_index=True, help_text='Numer zgłoszenia wyodrębniony z tematu lub treści wiadomości', max_length=50, null=True, verbose_name='Numer zgłoszenia'),
        ),
    ]
